FROM node:18-bullseye

WORKDIR /app

RUN npm init -y
RUN npm config set strict-ssl false

# Instala drivers SQL e IA no backend (onde devem ficar)
RUN npm install express mssql cors @google/genai --save

COPY api_server.js .

EXPOSE 8080

CMD ["node", "api_server.js"]