# Estágio 1: Build da Aplicação React
# Usando Node 20 (Debian) para garantir dependências do sistema
FROM node:20 as build

WORKDIR /app

# Configurações para evitar erros de rede/SSL no NPM
RUN npm config set strict-ssl false
RUN npm config set registry https://registry.npmjs.org/

COPY package.json ./

# Instala dependências de forma limpa, ignorando o lockfile antigo para evitar conflitos
RUN npm install --legacy-peer-deps --no-audit --no-package-lock

COPY . .

RUN npm run build

# Estágio 2: Nginx
FROM nginx:alpine
RUN rm -rf /etc/nginx/conf.d/*
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf.txt /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]